jobs:
- job: nGraph_ONNX_Lin

  # About 150% of total time
  timeoutInMinutes: 240

  pool:
    name: LIN_VMSS_VENV_EPHEMERAL_WU2

  variables:
    system.debug: true
    VSTS_HTTP_RETRY: 5
    VSTS_HTTP_TIMEOUT: 200
    WORKERS_NUMBER: 8
    BUILD_TYPE: Release
    REPO_DIR: $(Build.Repository.LocalPath)
    WORK_DIR: $(Pipeline.Workspace)/_w
    MODELS_DIR: /mnt/onnxtestdata/models
    TMP_DIR: /mnt/tmp

  steps:
  - script: |
      curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2019-06-01"
      whoami
      uname -a
      echo Python3 info ; which python3 ; python3 --version
      echo Python info ; which python ; python --version
      echo Java info ; which java ; java -version
      echo gcc info ; which gcc ; gcc --version
      lsb_release
      env
      cat /proc/cpuinfo
      cat /proc/meminfo
      cat /etc/fstab
      vmstat -s
      df
      lsblk -o NAME,HCTL,SIZE,MOUNTPOINT | grep -i "sd"
      free -h
    displayName: 'de'

  - checkout: self
    clean: true
    lfs: false
    submodules: recursive
    path: openvino

  - script: sudo rm -rf $(TMP_DIR) ; sudo mkdir $(TMP_DIR) ; sudo chmod 777 -R $(TMP_DIR)
    displayName: 'Create $(TMP_DIR)'
    enabled: true

  - script: sudo fallocate -l 48G /swapfile ; sudo mkswap /swapfile ; sudo swapon /swapfile ; free -h
    displayName: 'Create a swap and display swap space'
    enabled: true

  - script: ngraph/python/tests/test_onnx/model_zoo_preprocess.sh -d $(TMP_DIR) -o
    displayName: 'Clone ONNX models'
    enabled: true

  - script: ls -alR $(TMP_DIR)
    displayName: 'List $(TMP_DIR)'
    enabled: false

  - script: ls -alR $(MODELS_DIR)
    displayName: 'List $(MODELS_DIR)'
    enabled: false

  - script: ls -alR $(MODELS_DIR)/msft
    displayName: 'List $(MODELS_DIR)/msft'
    enabled: false

  - script: docker build --tag=openvino-onnx-ci-image --file=.ci/openvino-onnx/Dockerfile .
    displayName: 'Docker build'
    enabled: true

  - script: docker run --name openvino-onnx-ci-container --volume $(TMP_DIR)/model_zoo:/root/.onnx/model_zoo  --volume $(MODELS_DIR)/msft:/root/.onnx/model_zoo/MSFT openvino-onnx-ci-image
    displayName: 'Docker run'
    enabled: true

#  - script: docker run --name openvino-onnx-ci-container --volume $(TMP_DIR)/model_zoo:/root/.onnx/model_zoo openvino-onnx-ci-image
#    displayName: 'Docker run'
#    enabled: true
